# Sniperkit-Bot
# - Date: 2018-08-12 12:10:57.421452073 +0200 CEST m=+0.041161234
# - Status: analyzed

language: go

go:
  - 1.9.x
  - 1.10.x

go_import_path: github.com/sniperkit/snk.fork.go-billy.v4

install:
  - go get -v -t ./...

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
