# Sniperkit-Bot
# - Date: 2018-08-12 12:10:57.421452073 +0200 CEST m=+0.041161234
# - Status: analyzed

version: "{build}"
platform: x64

clone_folder: c:\gopath\src\gopkg.in\src-d\go-billy.v4

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go get -v -t ./...

build_script:
  - go test -v ./...
